package com.duckblade.osrs.sailing.features.barracudatrials;

import com.google.common.collect.ImmutableSet;
import java.util.Set;
import java.util.function.Supplier;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.DBTableID;
import net.runelite.api.gameval.ObjectID;

@RequiredArgsConstructor
enum TrialData
{
	JJ1(DBTableID.SailingBtTrialCore.Row.SAILING_BT_JUBBLY_JIVE, 1, () ->
		new Trial.Builder()
			.pt(2436.5f, 3018.5f)
			.pt(2429.25f, 3021.5f)
			.pt(2423.5f, 3021.5f)
			.pt(2396.75f, 3010.5f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_1)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_2)
			.pt(2392.5f, 3008.75f)
			.pt(2375.0f, 3008.75f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_3)
			.pt(2360.0f, 2993.75f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_4)
			.pt(2354.0f, 2979.25f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_5)
			.pt(2345.75f, 2975.75f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_6)
			.pt(2321.0f, 2975.75f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_7)
			.pt(2304.0f, 2975.75f)
			.pt(2298.25f, 2978.0f)
			.pt(2284.0f, 2978.0f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_8)
			.pt(2277.5f, 2984.5f)
			.pt(2267.25f, 2988.75f)
			.pt(2265.0f, 2988.75f)
			.pt(2251.0f, 2994.5f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_9)
			.pt(2245.25f, 3000.25f)
			.pt(2242.75f, 3006.5f)
			.pt(2242.75f, 3017.0f)
			.pt(2249.5f, 3023.75f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_10)
			.pt(2257.0f, 3023.75f)
			.pt(2281.0f, 2999.75f)
			.pt(2294.0f, 2999.75f)
			.pt(2299.25f, 3005.0f)
			.pt(2299.25f, 3012.0f)
			.pt(2307.25f, 3020.0f)
			.pt(2313.0f, 3020.0f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_11)
			.pt(2324.5f, 3020.0f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_12)
			.pt(2337.75f, 3006.75f)
			.pt(2352.0f, 3006.75f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_13)
			.pt(2359.0f, 2989.75f)
			.pt(2359.0f, 2961.0f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_14)
			.pt(2361.75f, 2954.25f)
			.pt(2367.5f, 2948.5f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_15)
			.pt(2377.5f, 2938.5f)
			.pt(2381.0f, 2940.0f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_16)
			.pt(2420.0f, 2940.0f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_17)
			.pt(2426.0f, 2940.0f)
			.pt(2439.0f, 2953.0f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_18)
			.pt(2434.75f, 2963.25f)
			.pt(2434.75f, 2977.0f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_19)
			.pt(2434.75f, 2982.0f)
			.pt(2438.0f, 2989.75f)
			.crate(ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_20)
			.pt(2434.5f, 2998.0f)
			.pt(2434.5f, 3011.0f)
			.pt(2439.5f, 3023.0f)
			.finish()
	),
	;

	@Getter
	private final int dbrow;

	@Getter
	private final int tier;

	private final Supplier<Trial.Builder> trial;

	public Trial buildTrial()
	{
		return new Trial(dbrow, tier, trial.get());
	}

	private static final TrialData[] values = values();

	public static TrialData findTrial(int dbrow, int tier)
	{
		for (var t : values)
		{
			if (t.dbrow == dbrow && t.tier == tier)
			{
				return t;
			}
		}

		return null;
	}

	static final Set<Integer> CARGO_OBJECTS = ImmutableSet.of(
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_1,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_2,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_3,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_4,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_5,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_6,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_7,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_8,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_9,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_10,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_11,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_12,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_13,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_14,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_15,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_16,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_17,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_18,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_19,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_20,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_21,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_22,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_23,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_24,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_25,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_26,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_27,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_28,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_29,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_30,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_31,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_32,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_33,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_34,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_35,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_36,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_37,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_38,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_39,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_40,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_41,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_42,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_43,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_44,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_45,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_46,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_47,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_48,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_49,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_50,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_51,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_52,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_53,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_54,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_55,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_56,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_57,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_58,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_59,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_60,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_61,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_62,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_63,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_64,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_65,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_66,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_67,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_68,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_69,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_70,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_71,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_72,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_73,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_74,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_75,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_76,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_77,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_78,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_79,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_80,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_81,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_82,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_83,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_84,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_85,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_86,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_87,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_88,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_89,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_90,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_91,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_92,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_93,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_94,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_95,
		ObjectID.SAILING_BT_GWENITH_GLIDE_COLLECTABLE_96,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_1,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_2,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_3,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_4,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_5,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_6,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_7,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_8,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_9,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_10,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_11,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_12,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_13,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_14,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_15,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_16,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_17,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_18,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_19,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_20,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_21,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_22,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_23,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_24,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_25,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_26,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_27,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_28,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_29,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_30,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_31,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_32,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_33,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_34,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_35,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_36,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_37,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_38,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_39,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_40,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_41,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_42,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_43,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_44,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_45,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_46,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_47,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_48,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_49,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_50,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_51,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_52,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_53,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_54,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_55,
		ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_56,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_1,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_2,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_3,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_4,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_5,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_6,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_7,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_8,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_9,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_10,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_11,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_12,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_13,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_14,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_15,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_16,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_17,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_18,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_19,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_20,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_21,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_22,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_23,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_24,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_25,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_26,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_27,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_28,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_29,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_30,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_31,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_32,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_33,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_34,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_35,
		ObjectID.SAILING_BT_TEMPOR_TANTRUM_COLLECTABLE_36
	);
}
